version: '3.4'

services:

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8000:80"
      #- "8000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8001:80"
      #- "8001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  ocelotapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    #links:
    #  - catalog.api
    #  - ordering.api
    depends_on:
      - catalog.api
      - ordering.api
    ports:
      - "8010:80"
      #- "8011:443"
      - "5010:5010"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
