version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  sale.api:
    image: ${DOCKER_REGISTRY-}saleapi
    build:
      context: .
      dockerfile: Sale.API/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: OcelotAPIGateway/Dockerfile

  elasticsearch:
    image: elasticsearch:7.9.2

  kibana:
    image: kibana:7.9.2

volumes:
  elasticsearch-data: